apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-3vsf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-3vsf@sha256:cf5291a361056473ed1bf4b75d3448dec3eddb7b99cadc1a7a482e7c91abb472
        name: my-nodejs
        resources: {}
status: {}
